### ISSUE TITLE
About the README

### ISSUE THREAD

**Issue by xpgeng** [jessamynsmith/django-celery-example#1]
Hi, I was trying this tool. It is very helpful, however, there are some steps I cannot understand. 

- In the README, what I should do to follow this step `Edit the Site to have the correct localhost url`?
  - Add what kind of url to the object `sites` ?
After login in.
- In `social account`, Must I use the same user name in Twitter? or I just type the account I created in this django app.
    - `Extra data` is for what?
- What's the `Provider` means in social application? Just select `Twitter`?
- `Name` is the my Twitter username? 

Thanks very much.

**Comment by jessamynsmith** [comment]
If you refer to the Django documentation, you can see the explanation of the Sites framework: [https://docs.djangoproject.com/en/2.1/ref/contrib/sites/#django.contrib.sites.models.Site](https://docs.djangoproject.com/en/2.1/ref/contrib/sites/#django.contrib.sites.models.Site)

The Django Allauth docs explain each provider, including twitter, and how to set them up: [https://django-allauth.readthedocs.io/en/latest/providers.html#twitter](https://django-allauth.readthedocs.io/en/latest/providers.html#twitter)
